[package]
name = "metal_knight"
version = "0.1.0"
edition = "2024"

[dependencies]
tract-onnx = "0.22.0"
image = "0.25.9"
salvo = {  version = "0.85.0", features = ["oapi", "compression"] }
tokio = { version = "1.48.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
